# Mathematics(Linear Algebra)

##### Import relevant libraries 

In [1]:
import numpy as np

###### We will impelment Scalars, Vectors, Metrcies and take some information about each one of them

<img src="R.png">

##### Scalars

Scalars are metrcies with only one element,
and every number in Linear Algebra are refered as scalar.
_________________________________________________________

What make Scalars unique is they're are having 0D which mean zero dimension and with geometry that's mean that scalar
we can refer to it in geometry as point that have no direction so,
Scalar is 0D = Point = no direction 

_________________________________________________________

In [4]:
Scalar = [5]

In [5]:
Scalar

[5]

##### Vectors

We can say that Matrcies are a collection of Vectors
Vectors have 2 types, The row and Column we need to know the Length of the Vector
which is the number of element inside the Vector
_________________________________________________________

Vectors are 1D one dimensoinal in geometry we can refer to Vector as a Line that have a direction 
Vectors could be a collection of lines with multiple directions
Vector Column type are M * 1, 
Vector Row type are 1 * M

In [8]:
Vector = np.array([2, -4, 9])

In [9]:
Vector

array([ 2, -4,  9])

So now we need to see how we can craft a Vector column type
and Vector Row type

In [16]:
# Vector Row type 1 * M
Vector.reshape(1, 3)

array([[ 2, -4,  9]])

In [17]:
# Vector Column type M * 1
Vector.reshape(3, 1)

array([[ 2],
       [-4],
       [ 9]])

##### Matrcies

Matrcie [A] could be m by n array,
so[A] could be 3 rows and 4 columns

In [10]:
Matrcie = np.array([[5, 12, 6], [-3, 0, 14]])

In [11]:
Matrcie

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
# Checking the shape of the array it should return 2 rows and 3 columns
Matrcie.shape

(2, 3)

##### Tensors

Tensors are the general concepts about everything we explored till now in this notebook
We can say Vectors and Scalars and Matrcies are Tensors and Tensor is a collection of Matrcies
Tensors could be K * M * N and we will now try to combine two matrcies to creat a Tensor
We should also know that Scalars are Tensors from Rank0,
Vectors are Tensors from Rank1,
Matrcies are Tensors from Rank2

In [20]:
m1 =np.array([[5,12,6], [-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [21]:
m2 =np.array([[9, 8, 7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [27]:
Tensor=np.array([m1,m2])
Tensor


array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [28]:
# Checking it's dimensions to recheck our past info about Tensors have K*M*N
Tensor.shape

(2, 2, 3)

### Now it's time to learn how to add and substract different Matrcies

First of all the chossen Matrcies should have the same Dimensions

#### Addition

In [33]:
# If we have two matrcies
Matrcie_1=np.array([[5,12,6], [-3,0,14]])
Matrcie_2=np.array([[9,8,7], [1,3,-5]])

In [34]:
# We will check their dimesnons to make sure they're the same
Matrcie_1.shape

(2, 3)

In [35]:
Matrcie_2.shape

(2, 3)

Adding up the element we will have element number one in matrcie_1 and matrcie_2 will result in the new matrcie 
is 5+9 will result 14 and that will be the new element in the new matrcie

In [38]:
# Simply we will ad it like that
New_Matrcie=[Matrcie_1+Matrcie_2]
New_Matrcie

[array([[14, 20, 13],
        [-2,  3,  9]])]

#### Subtraction

In [47]:
# Here we have two examples of matrcies
Matrcie_one=np.array([[5,3],[-2,4]])
Matrcie_two=np.array([[7,-5],[3,8]])
# Checking the shape of matrcies
Matrcie_one.shape
Matrcie_one.shape

(2, 2)

In [48]:
# The same rules in the addition operations applies here too
#We will jst do this
Sub_Matrcie=(Matrcie_one - Matrcie_two)
Sub_Matrcie

array([[-2,  8],
       [-5, -4]])